### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by adityatadadikar** [IBM/cognitive-moderator-service#13]
I'm getting an error of 500 while posting url of my api on slack "Request URl" section. Its showing my url is not validate.
![error3](https://user-images.githubusercontent.com/47084145/51803391-a4568980-227a-11e9-94f3-c894d7e3f74d.PNG)

**Comment by sanjeevghimire** [comment]
make sure the url is exposed and slack can access it.

**Comment by adityatadadikar** [comment]
Okay sir I will try.

Thank you sir.

**Comment by sanjeevghimire** [comment]
closing it as its not the code issue
