### ISSUE TITLE
NLU_api

### ISSUE THREAD

**Issue by adityatadadikar** [IBM/cognitive-moderator-service#14]
NLU service is now provided with api key instead of username and password. What changes i have to do in code?
![error4](https://user-images.githubusercontent.com/47084145/51803470-92c1b180-227b-11e9-8875-3a917de8d195.PNG)

**Comment by sanjeevghimire** [comment]
I have made the changes. The fix will be deployed.

**Comment by adityatadadikar** [comment]
Thanks a lot sir!!!

**Comment by sanjeevghimire** [comment]
#23 will solve this. Closing.
