### ISSUE TITLE
code_result

### ISSUE THREAD

**Issue by adityatadadikar** [IBM/cognitive-moderator-service#15]
![error5](https://user-images.githubusercontent.com/47084145/51803595-00221200-227d-11e9-948d-2ce777260109.PNG)

**Comment by sanjeevghimire** [comment]
the issue is because you haven't supplied input parameters such as message_text or image.

**Comment by adityatadadikar** [comment]
Okay sir.

Thank you.

**Comment by sanjeevghimire** [comment]
see #23
