### ISSUE TITLE
Object of type DetailedResponse is not JSON serializable

### ISSUE THREAD

**Issue by upkarlidder** [IBM/cognitive-moderator-service#20]
The issue is that response of type DetailedResponse and not serializable. Need to call get_results() on it to get the actual JSON result object. This will also fix `DetailedResponse does not have attribute get` error on line 123. 

**Creating PR.**

https://github.com/IBM/cognitive-moderator-service/blob/master/functions/bot_moderator_function.py#L123

```
    "2019-01-29T04:11:28.808556283Z stderr: File \"/action/1/src/main__.py\", line 122, in main",
    "2019-01-29T04:11:28.80886719Z  stderr: print('response:'+json.dumps(response, indent=2))",
    "2019-01-29T04:11:28.808874836Z stderr: File \"/usr/local/lib/python3.7/json/__init__.py\", line 238, in dumps",
    "2019-01-29T04:11:28.80887967Z  stderr: **kw).encode(obj)",
    "2019-01-29T04:11:28.808884211Z stderr: File \"/usr/local/lib/python3.7/json/encoder.py\", line 201, in encode",
    "2019-01-29T04:11:28.808899403Z stderr: chunks = list(chunks)",
    "2019-01-29T04:11:28.808904451Z stderr: File \"/usr/local/lib/python3.7/json/encoder.py\", line 438, in _iterencode",
    "2019-01-29T04:11:28.808908996Z stderr: o = _default(o)",
    "2019-01-29T04:11:28.808913483Z stderr: File \"/usr/local/lib/python3.7/json/encoder.py\", line 179, in default",
    "2019-01-29T04:11:28.808917881Z stderr: raise TypeError(f'Object of type {o.__class__.__name__} '",
    "2019-01-29T04:11:28.808922437Z stderr: TypeError: Object of type DetailedResponse is not JSON serializable",
    "2019-01-29T04:11:28.808926873Z stderr: "
```

See here: https://cloud.ibm.com/apidocs/natural-language-understanding?language=python#data-handling

![image](https://user-images.githubusercontent.com/3187457/51883917-e72b6680-2339-11e9-82c2-6ea1b0dfcfef.png)

**Comment by upkarlidder** [comment]
Create PR https://github.com/IBM/cognitive-moderator-service/pull/21

**Comment by sanjeevghimire** [comment]
the issue is related to python runtime. Existing code works fine with python 3.6 as instructed in the readme. #23 addresses this.
