### ISSUE TITLE
Event Subscriptions page does not save without a request URL

### ISSUE THREAD

**Issue by upkarlidder** [IBM/cognitive-moderator-service#24]
The readme states `For now leave the Request URL empty. We will fill it in when the IBM Cloud Function is exposed through an API.` However, I cannot leave the page without entering the URL. If I do, all the information I entered is blanked out.

I suggest moving the `Events Subscription` steps to after creating the API URL. The rest of the slack instructions can be done before.

**Comment by sanjeevghimire** [comment]
@lidderupk  I was able to leave it empty

**Comment by sanjeevghimire** [comment]
And there is instruction at the end after the API is created to update the request URL
